services:
  postgres:
    image: ghcr.io/tensorchord/vchord-postgres:pg18-v1.0.0
    environment:
      POSTGRES_PASSWORD: loopdedupedev
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/18/docker

volumes:
  postgres:
